# Generated by Django 5.0.3 on 2024-03-08 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0006_message_to_alter_message_room_alter_message_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceCode', models.CharField(max_length=50, unique=True)),
                ('ServiceName', models.CharField(max_length=225)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='US_Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskName', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='STAFF', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FloorName', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='STAFF', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='ACTIVE', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='ACTIVE', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('US_Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.us_menu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('Type', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='ACTIVE', max_length=100)),
                ('Price', models.IntegerField(default=0, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('OrderOnline', models.BooleanField(blank=True, default=True, null=True)),
                ('Discount', models.IntegerField(blank=True, default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.photos')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('US_MenuType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.us_menutype')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderCode', models.CharField(blank=True, default='', max_length=100)),
                ('payVAT', models.IntegerField(blank=True, default=0)),
                ('isAccepted', models.BooleanField(blank=True, default=False, null=True)),
                ('isShiped', models.BooleanField(blank=True, default=False, null=True)),
                ('isCompleted', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('US_Desk', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.us_desk')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_OrdersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.IntegerField(default=0, null=True)),
                ('Price', models.IntegerField(default=0, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('US_MenuItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.us_menuitems')),
                ('US_Orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.us_orders')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='STAFF', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('US_Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.us_floor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='us_orders',
            name='US_Rooms',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.us_rooms'),
        ),
        migrations.AddField(
            model_name='us_desk',
            name='US_Rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.us_rooms'),
        ),
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='ACTIVE', max_length=100, null=True)),
                ('Name', models.CharField(max_length=225)),
                ('Hotline', models.CharField(max_length=100)),
                ('Facebook', models.CharField(max_length=100)),
                ('IsPublic', models.BooleanField(default=True)),
                ('adr_tinh', models.CharField(blank=True, default='', max_length=100)),
                ('adr_thanhpho', models.CharField(blank=True, default='', max_length=100)),
                ('adr_huyen', models.CharField(blank=True, default='', max_length=100)),
                ('adr_xa', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ServiceCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='us_orders',
            name='UserServices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.userservices'),
        ),
        migrations.AddField(
            model_name='us_menu',
            name='UserServices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.userservices'),
        ),
        migrations.CreateModel(
            name='US_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF')], default='STAFF', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add', to=settings.AUTH_USER_MODEL)),
                ('UserServices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.userservices')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='US_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, default='', max_length=100)),
                ('Action', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('UserServices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.userservices')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='us_floor',
            name='UserServices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipays.userservices'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherCode', models.CharField(max_length=100, unique=True)),
                ('Type', models.CharField(blank=True, choices=[('Percent', 'Percent'), ('Price', 'Price')], default='Percent', max_length=100)),
                ('Value', models.IntegerField(blank=True, null=True)),
                ('MaxPrice', models.IntegerField(blank=True, null=True)),
                ('LimitUses', models.IntegerField(blank=True, null=True)),
                ('LimitHours', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('US_MenuItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.us_menuitems')),
                ('UserServices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.userservices')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
