# Generated by Django 5.0.3 on 2024-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0009_alter_photos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.TextField(),
        ),
    ]
