# Generated by Django 5.0.3 on 2024-03-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0010_alter_photos_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservices',
            old_name='adr_thanhpho',
            new_name='adr_details',
        ),
        migrations.AddField(
            model_name='userservices',
            name='Avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipays.photos'),
        ),
        migrations.AddField(
            model_name='userservices',
            name='Zalo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userservices',
            name='adr_thon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userservices',
            name='Facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userservices',
            name='Hotline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
