# Generated by Django 5.0.3 on 2024-03-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0011_rename_adr_thanhpho_userservices_adr_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservices',
            name='Sologan',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
