# Generated by Django 5.0.3 on 2024-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0012_userservices_sologan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adr_details',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adr_full',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userservices',
            name='adr_full',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
