# Generated by Django 5.0.3 on 2024-04-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0013_userprofile_adr_details_userprofile_adr_full_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adr_thanhpho',
        ),
        migrations.RemoveField(
            model_name='userservices',
            name='adr_thon',
        ),
    ]
