# Generated by Django 5.0.3 on 2024-04-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0014_remove_userprofile_adr_thanhpho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservices',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
