# Generated by Django 5.0.3 on 2024-04-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0015_userservices_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us_member',
            old_name='user_add',
            new_name='user',
        ),
    ]
