# Generated by Django 5.0.3 on 2024-05-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0017_ipays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us_menuitems',
            name='Photos',
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='Avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Avatar', to='ipays.photos'),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='Background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Background', to='ipays.photos'),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='IsActive',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('NOTACTIVE', 'NOTACTIVE')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='ShortDescription',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='Tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='TypeDetails',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='pictures1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures1', to='ipays.photos'),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='pictures2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures2', to='ipays.photos'),
        ),
        migrations.AddField(
            model_name='us_menuitems',
            name='pictures3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures3', to='ipays.photos'),
        ),
        migrations.AlterField(
            model_name='us_menuitems',
            name='Type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
